bettermarks_proxy_enabled_instances:
  - apm
  - school
  - translations
  - apps
  - events
  - csp-report
bettermarks_subdomains:
  apm: apm
  school: school
  apps: apps
  events: events
  translations: translations
bettermarks_proxy_subdomains:
  apm: apm
  school: school
  apps: apps
  events: events
  translations: translations
  csp: csp-report
bettermarks_domain: bettermarks.com
proxy_identification_header: "x-schulcloud-proxy"
bettermarks_proxy_ingress_enabled: false
bettermarks_proxy_ingress_tls: false
bettermarks_proxy_ingress_annotations: {}
bettermarks_proxy_chart_values:
  replicaCount: 1
  containerSecurityContext:
    enabled: true
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 100Mi
  serviceAccount:
    create: true
  service:
    type: ClusterIP
  metrics:
    enabled: false
  ingress:
    enabled: "{{ bettermarks_proxy_ingress_enabled }}"
    tls: "{{ bettermarks_proxy_ingress_tls }}"
    annotations: "{{ bettermarks_proxy_ingress_annotations }}"
